//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Choice
    {
        public Choice()
        {
            this.TestXPapers = new HashSet<TestXPaper>();
        }
    
        public int Id { get; set; }
        public int QuestionId { get; set; }
        [Required]
        public string Label { get; set; }
        public int Points { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<TestXPaper> TestXPapers { get; set; }
    }
}
