//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.TestXPapers = new HashSet<TestXPaper>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TestId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public Nullable<System.TimeSpan> TokenExpireTime { get; set; }
        public Nullable<decimal> MarkScored { get; set; }
        public Nullable<decimal> MaximumMarks { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; } 
        public virtual ICollection<TestXPaper> TestXPapers { get; set; }
    }
}
