//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestXQuestion
    {
        public TestXQuestion()
        {
            this.TestXPapers = new HashSet<TestXPaper>();
        }
    
        public int Id { get; set; }
        public int TestId { get; set; }
        public int QuestionId { get; set; }
        public int QuestionNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Test Test { get; set; }
        public virtual ICollection<TestXPaper> TestXPapers { get; set; }
    }
}
