//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.Registrations = new HashSet<Registration>();
            this.TestXQuestions = new HashSet<TestXQuestion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.TimeSpan> DurationInMinute { get; set; }
    
        public virtual ICollection<Registration> Registrations { get; set; }
        public virtual ICollection<TestXQuestion> TestXQuestions { get; set; }
    }
}
